# Generated by Django 5.2.4 on 2025-07-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes_UA_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ua', models.CharField(max_length=100)),
                ('description_ua', models.TextField()),
                ('instruction_ua', models.TextField()),
                ('name_en', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('instruction_en', models.TextField()),
                ('img', models.CharField()),
            ],
        ),
    ]
