# Generated by Django 5.2.4 on 2025-08-23 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_straw', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_straw.recipes_ua_en')),
                ('user', models.ManyToManyField(auto_created=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
