# Generated by Django 5.2.4 on 2025-08-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_straw', '0002_commentusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentusers',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
