# Generated by Django 5.2.4 on 2025-09-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_straw', '0002_customuser_code_user_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photos_profil',
            field=models.ImageField(default='img_profil/default.jpg', upload_to='img_profil/'),
        ),
    ]
