# Generated by Django 5.2.4 on 2025-09-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_straw', '0003_customuser_photos_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('default_user', 'Default User'), ('editior_user', 'Editior User')], default='default_user', max_length=100),
        ),
    ]
