# Generated by Django 5.2.4 on 2025-09-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_straw', '0005_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('default', 'Default User'), ('editior', 'Editior User'), ('admin', 'Admin User'), ('moderator', 'Moderator User'), ('banned', 'Banned User')], default='default_user', max_length=100),
        ),
    ]
