# Generated by Django 5.2.4 on 2025-08-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_straw', '0006_castomuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CastomUser',
        ),
    ]
