# Generated by Django 5.2.4 on 2025-08-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_straw', '0007_delete_castomuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentusers',
            name='comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
